### ISSUE TITLE
onClose prop throws error when not used..I think it should be an optional prop

### ISSUE THREAD

**Issue by WalidKurchied** [pradel/react-responsive-modal#311]
I think on **onClose** prop should be optional the reason i think that is because if a user doesn't want the close icon like in my case i wanted to have my own close and confirm buttons i don't need the onClose button anymore in this case so i got rid of it however because its required it was thrown an error in the console thats why i think it should be optional and leave the open prop as required as it will determine wether or not the modal should show or not.

I understand the onClose is used to exit if the user clicks on the modal overlay or when the user clicks on the X icon or when the user hits the Esc button but what if user doesn't want any of these functionalities.

My work around to get rid of the error when not using **onClose** is to implement an empty onClose function `onClose={() => null}` or `onClose={() => {}}`.

Thanks.

**Comment by pradel** [comment]
@WalidKurchied I understand your use case but this is not a common way to use the lib. I am afraid that if I remove the mandatory `onClose` property users might be confused, so you can either use an empty function as you did or just provide the same function that you pass to your close button, since the callback will not be called it shouldn't be a problem :)
