### ISSUE TITLE
Using scroll bar to scroll through content on long modal closes the modal

### ISSUE THREAD

**Issue by peterlazzarino** [pradel/react-responsive-modal#43]
Issue shown here with long modal, try to scroll down to view content. https://codesandbox.io/s/jlzkm0jo3v

Users can't use scrollbar to view long content without inadvertently closing the modal. Browser chrome with

package version: 2.0.0

**Comment by pradel** [comment]
You are using the `little` props which is used for little modal only if you remove that prop it should work :)

**Comment by peterlazzarino** [comment]
@pradel it still doesn't work, just updated my fork. The version my team is using doesn't use it either. I created a PR to fix the issue.

**Comment by pradel** [comment]
Oh okay sorry indeed you are right will take a look at it!

**Comment by peterlazzarino** [comment]
Thanks! I ran some tests with my fix and it should be all set.

**Comment by pradel** [comment]
Published as `2.0.1` thanks!

**Comment by timkingman** [comment]
I'm still seeing this issue on 2.0.1, with Chrome (65.0.3325.181 x64) on Windows (7).
My modal content is tall, but my main page doesn't scroll. Clicking on the scroll bar still closes the window in Peter's codesandbox in the first comment, even after switching it to r-r-m 2.0.1.

I can also reproduce this on https://react-responsive-modal.leopradel.com/ after removing everything below the examples so the main page doesn't scroll.
1. https://react-responsive-modal.leopradel.com/
2. In Chrome dev tools, run:
`$('.main-content').removeChild($('.main-content > div:not(.examples)')); 
$('.main-content').removeChild($('.main-content > footer'))`
3. If necessary, resize your window so there are no scroll bars.
4. Click the Open button for the "Big modal" example.
5. Click on the scroll bar that just appeared and try to scroll.

Expected: page scrolls with modal in it. (This works when scrolling with a mouse wheel.)
Actual: modal closes.

It looks like when the main page content doesn't scroll, `document.documentElement.offsetWidth` matches `window.innerWidth` as the full width of the window. When the main page content has a scrollbar, these widths differ and Peter's patch works to detect clicks in the vertical scrollbar.

In my case, where the page doesn't scroll but the modal causes a scrollbar to appear, the .scrollWidth of the overlay is less then window.innerWidth. I think this makes sense, because the modal is nested inside the overlay, so if the modal's content is tall, the overlay gets a scroll bar.

I've only tested my pull request in Chrome 65 and IE 11, but it looks good on both.
