### ISSUE TITLE
onClose method is called on "Esc" when it is closed

### ISSUE THREAD

**Issue by spiderhands** [pradel/react-responsive-modal#91]
Hi. First of all thank you for such a great modal! 

Our team is using it and we faced an issue today. There is a problem with onClose method. When you press "Esc" is called even if the modal is in "hidden" state ( open = false ). Here is [an example](https://codesandbox.io/s/rm4mvv8ryo).

Here is a [pull request](https://github.com/pradel/react-responsive-modal/pull/90) to fix it.

## Environment

| Tech                   | Version |
| ---------------------- | ------- |
| react-responsive-modal |  2.0.1 |
| React                  | 16.1.1  |
| browser                |  *  |

**Comment by pradel** [comment]
Hi! Thanks for the pull request :)

I noticed this issue. I fixed it on master but I can't release a new major version for now because I am using `react-lifecycles-compat` which is not compatible with `react-jss` for now.

If you want me to release a 2.x version with the fix can you please point the pull request to the v2 branch?

Thanks!

**Comment by spiderhands** [comment]
ok, [here is PR to v2](https://github.com/pradel/react-responsive-modal/pull/92)

**Comment by pradel** [comment]
Thanks! published as 2.0.3 :)
